project:
  type: website

lang: es
date-format: iso

execute:
  freeze: auto

website:
  title: "Biología de las Plantas, 2025-2"
  description: |
    Sitio web del curso Biología de las Plantas (2025-2) del Instituto de Biología de la Universidad de Antioquia. 
  site-url: https://biologia-plantas.github.io/2025-2/
  repo-url: https://github.com/biologia-plantas/2025-2/
  favicon: imagenes/bldp.png
  image: imagenes/bldp.png
  # repo-actions: [edit, source, issue]

  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  google-analytics:
    tracking-id: "G-H1C9C97SS0"
    anonymize-ip: true

  twitter-card:
    creator: "@alexespinosaco"
    card-style: summary_large_image

  open-graph: true

  sidebar:
    style: docked
    logo: imagenes/bldp.png
    search: true
    pinned: true
    align: center

    tools: 
      - text: "Repositorio"
        icon: github
        href: https://github.com/biologia-plantas/2025-2/
      - text: "Manual de laboratorio"
        icon: book
        href: https://geobota.github.io/biologia-plantas-manual/
      # - text: "Google Classroom"
      #   icon: layout-text-window-reverse
      #   href: https://classroom.google.com/u/1/c/NzUwNTI3OTE5NDI3
      # - text: "Google Meet"
      #   icon: person-video
      #   href: https://meet.google.com/zrq-rtri-der

    contents:
      - section: "Información del curso"
        contents:
          - text: "Inicio"
            href: index.qmd
          - text: "Manual de laboratorio"
            href: https://geobota.github.io/biologia-plantas-manual/
          # - text: "Google Classroom"
          #   href: https://classroom.google.com/u/1/c/NzUwNTI3OTE5NDI3
          # - text: "Google Meet"
          #   href: https://meet.google.com/zrq-rtri-der
          - text: "Enlaces de utilidad"
      - section: "Teoría"
        contents:
          - text: "Introducción al curso"
            href: presentaciones/introduccion-curso/
          - text: "Introducción a la botánica"
            href: presentaciones/introduccion-botanica/
          # - text: "Citología"
          #   href: presentaciones/citologia/
          # - text: "Histología"
          #   href: presentaciones/histologia/
          # - text: "Diversidad"
          #   href: presentaciones/diversidad/
          # - text: "Raíz"
          #   href: presentaciones/raiz/
          # - text: "Tallo"
          #   href: presentaciones/tallo/
          # - text: "Hoja"
          #   href: presentaciones/hoja/
          # - text: "Flor"
          #   href: presentaciones/flor/
      - section: "Laboratorio"
        contents:
          # - text: "Introducción al laboratorio"
          #   href: presentaciones/introducción-laboratorio/
          # - text: "Recorrido"
          #   href: presentaciones/recorrido/
          # - text: "Citología"
          #   href: presentaciones/citologia-laboratorio/
          # - text: "Histología"
          #   href: presentaciones/histologia-laboratorio/
          # - text: "Diversidad"
          #   href: presentaciones/diversidad-laboratorio/
          # - text: "Raíz"
          #   href: presentaciones/raiz-laboratorio/
          # - text: "Tallo"
          #   href: presentaciones/tallo-laboratorio/
          # - text: "Hoja"
          #   href: presentaciones/hoja-laboratorio/
          # - text: "Flor"
          #   href: presentaciones/flor-laboratorio/
          # - text: "Fruto"
          #   href: presentaciones/fruto-laboratorio/

  page-footer: 
    left: Álex Espinosa-Correa © 2025. Este sitio web está bajo una licencia [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    right: Hecho por [\@alexespinosaco](https://alexespinosaco.github.io) con [![](https://www.r-project.org/logo/Rlogo.svg){fig-alt="R" width=21px}](https://www.r-project.org/) y [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

csl: apa.csl

crossref: 
  fig-title: Fig

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    css: styles.scss
    mainfont: "Atkinson Hyperlegible"
    respect-user-color-scheme: true
